version: '3.0'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
    - 5672:5672 # port for the daemon API
    - 15672:15672 # port for the RabbitMQ management interface
  standalone_consumer:
    build: standalone_consumer
    links:
    - rabbitmq
    command: python consumer.py -p 5672 -s rabbitmq
  standalone_producer:
    build: standalone_producer
    links:
    - rabbitmq
    # run the producer sending random messages -r times
    command: python producer.py -p 5672 -s rabbitmq -r ${Message_Count}
