{{- if .Values.producer.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "producer.fullname" . }}
  labels:
    {{- include "producer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.producer.replicaCount }}
  selector:
    matchLabels:
      {{- include "producer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "producer.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.producer.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "rabbitmq-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ template "producer.fullname" . }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: {{ .Values.producer.image.repository }}
        imagePullPolicy: {{ .Values.producer.image.pullPolicy }}
        env:
        - name: {{ .Values.producer.env.name }}
          value: "{{ .Values.producer.env.value }}"
        command: ["python", "producer.py", "-p", "{{ .Values.rabbitmq.ports.containerPortAPI }}", "-s", "{{ template "rabbitmq-server.fullname" . }}"]
        args: ["-r", "$({{ .Values.producer.env.name }})"]
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      {{- with .Values.nodeSelector }}
      restartPolicy: {{ .Values.producer.image.restartPolicy }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}