{{- if .Values.consumer.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "consumer.fullname" . }}
  labels:
    {{- include "consumer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.consumer.replicaCount }}
  selector:
    matchLabels:
      {{- include "consumer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "consumer.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.consumer.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "rabbitmq-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ template "consumer.fullname" . }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: {{ .Values.consumer.image.repository }}
        imagePullPolicy: {{ .Values.consumer.image.pullPolicy }}
        command: ["python", "consumer.py", "-p", "{{ .Values.rabbitmq.ports.containerPortAPI }}", "-s", "{{ template "rabbitmq-server.fullname" . }}"]
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      {{- with .Values.nodeSelector }}
      restartPolicy: {{ .Values.consumer.image.restartPolicy }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}