apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rabbitmq.service.name }}
  labels:
    {{- include "rabbitmq-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.rabbitmq.service.type }}
  ports:
  - name: {{ .Values.rabbitmq.service.APIportname }}
    port: {{ .Values.rabbitmq.service.APIport }}
    targetPort: {{ .Values.rabbitmq.service.APItargetPort }}
    protocol: {{ .Values.rabbitmq.service.APIportprotocol }}

  - name: {{ .Values.rabbitmq.service.GUIportname }}
    port: {{ .Values.rabbitmq.service.GUIport }}
    targetPort: {{ .Values.rabbitmq.service.GUItargetPort }}
    protocol: {{ .Values.rabbitmq.service.GUIportprotocl }}

  selector:
    {{- include "rabbitmq-chart.selectorLabels" . | nindent 4 }}
